name: furi
version: 0.0.1
author: Nanonid <eric.lindahl.tab@gmail.com>
description: FUri -- the functional URI; exposes the building blocks of the core with a functional interface.
homepage: https://github.com/Nanonid/furi
dev_dependencies:
  unittest: any
