name: furi
version: 0.0.3
author: Nanonid <eric.lindahl.tab@gmail.com>
description: |-
  FUri - the functional URI
  Exposes the dart:core URI with a fluent functional interface.
homepage: https://github.com/Nanonid/furi
dev_dependencies:
  unittest: any
